/**
 *@Generated by sagacity-quickvo 4.16
 */
package com.strict.modules.system.vo;

import java.io.Serializable;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.time.LocalDateTime;

/**
 * @project sqltoy-strict
 * @version 1.0.0
 * ,Remark:权限表  
 */
@ApiModel(value="AuthorityVO",description="权限表")
public class AuthorityVO implements Serializable {
	
	/**
	 * 
	 */
	private static final long serialVersionUID = 6365434985152539607L;
	
/*---begin-auto-generate-don't-update-this-area--*/	
   /**
	 * 
	 */
	@ApiModelProperty(value="",allowEmptyValue=false)
	private String auId;
	
   /**
	 * 
	 */
	@ApiModelProperty(value="",allowEmptyValue=false)
	private String auCode;
	
   /**
	 * 
	 */
	@ApiModelProperty(value="",allowEmptyValue=false)
	private String auPcode;
	
   /**
	 * 
	 */
	@ApiModelProperty(value="",allowEmptyValue=false)
	private String auName;
	
   /**
	 * 
	 */
	@ApiModelProperty(value="",allowEmptyValue=true)
	private String auType;
	
   /**
	 * 
	 */
	@ApiModelProperty(value="",allowEmptyValue=true)
	private String auNote;
	
   /**
	 * 
	 */
	@ApiModelProperty(value="",allowEmptyValue=true)
	private String createBy;
	
   /**
	 * 
	 */
	@ApiModelProperty(value="",allowEmptyValue=true)
	private LocalDateTime createTime;
	
   /**
	 * 
	 */
	@ApiModelProperty(value="",allowEmptyValue=true)
	private String updateBy;
	
   /**
	 * 
	 */
	@ApiModelProperty(value="",allowEmptyValue=true)
	private LocalDateTime updateTime;
	
   /**
	 * 
	 */
	@ApiModelProperty(value="",allowEmptyValue=true)
	private Integer delflag;
	
   /**
	 * 
	 */
	@ApiModelProperty(value="",allowEmptyValue=true)
	private String nodeRoute;
	
   /**
	 * 
	 */
	@ApiModelProperty(value="",allowEmptyValue=true)
	private Integer nodeLevel;
	
   /**
	 * 
	 */
	@ApiModelProperty(value="",allowEmptyValue=true)
	private Integer isLeaf;
	
	
	/**
	 *@param auId the auId to set
	 */
	public AuthorityVO setAuId(String auId) {
		this.auId=auId;
		return this;
	}
		
	/**
	 *@return the AuId
	 */
	public String getAuId() {
	    return this.auId;
	}
	
	/**
	 *@param auCode the auCode to set
	 */
	public AuthorityVO setAuCode(String auCode) {
		this.auCode=auCode;
		return this;
	}
		
	/**
	 *@return the AuCode
	 */
	public String getAuCode() {
	    return this.auCode;
	}
	
	/**
	 *@param auPcode the auPcode to set
	 */
	public AuthorityVO setAuPcode(String auPcode) {
		this.auPcode=auPcode;
		return this;
	}
		
	/**
	 *@return the AuPcode
	 */
	public String getAuPcode() {
	    return this.auPcode;
	}
	
	/**
	 *@param auName the auName to set
	 */
	public AuthorityVO setAuName(String auName) {
		this.auName=auName;
		return this;
	}
		
	/**
	 *@return the AuName
	 */
	public String getAuName() {
	    return this.auName;
	}
	
	/**
	 *@param auType the auType to set
	 */
	public AuthorityVO setAuType(String auType) {
		this.auType=auType;
		return this;
	}
		
	/**
	 *@return the AuType
	 */
	public String getAuType() {
	    return this.auType;
	}
	
	/**
	 *@param auNote the auNote to set
	 */
	public AuthorityVO setAuNote(String auNote) {
		this.auNote=auNote;
		return this;
	}
		
	/**
	 *@return the AuNote
	 */
	public String getAuNote() {
	    return this.auNote;
	}
	
	/**
	 *@param createBy the createBy to set
	 */
	public AuthorityVO setCreateBy(String createBy) {
		this.createBy=createBy;
		return this;
	}
		
	/**
	 *@return the CreateBy
	 */
	public String getCreateBy() {
	    return this.createBy;
	}
	
	/**
	 *@param createTime the createTime to set
	 */
	public AuthorityVO setCreateTime(LocalDateTime createTime) {
		this.createTime=createTime;
		return this;
	}
		
	/**
	 *@return the CreateTime
	 */
	public LocalDateTime getCreateTime() {
	    return this.createTime;
	}
	
	/**
	 *@param updateBy the updateBy to set
	 */
	public AuthorityVO setUpdateBy(String updateBy) {
		this.updateBy=updateBy;
		return this;
	}
		
	/**
	 *@return the UpdateBy
	 */
	public String getUpdateBy() {
	    return this.updateBy;
	}
	
	/**
	 *@param updateTime the updateTime to set
	 */
	public AuthorityVO setUpdateTime(LocalDateTime updateTime) {
		this.updateTime=updateTime;
		return this;
	}
		
	/**
	 *@return the UpdateTime
	 */
	public LocalDateTime getUpdateTime() {
	    return this.updateTime;
	}
	
	/**
	 *@param delflag the delflag to set
	 */
	public AuthorityVO setDelflag(Integer delflag) {
		this.delflag=delflag;
		return this;
	}
		
	/**
	 *@return the Delflag
	 */
	public Integer getDelflag() {
	    return this.delflag;
	}
	
	/**
	 *@param nodeRoute the nodeRoute to set
	 */
	public AuthorityVO setNodeRoute(String nodeRoute) {
		this.nodeRoute=nodeRoute;
		return this;
	}
		
	/**
	 *@return the NodeRoute
	 */
	public String getNodeRoute() {
	    return this.nodeRoute;
	}
	
	/**
	 *@param nodeLevel the nodeLevel to set
	 */
	public AuthorityVO setNodeLevel(Integer nodeLevel) {
		this.nodeLevel=nodeLevel;
		return this;
	}
		
	/**
	 *@return the NodeLevel
	 */
	public Integer getNodeLevel() {
	    return this.nodeLevel;
	}
	
	/**
	 *@param isLeaf the isLeaf to set
	 */
	public AuthorityVO setIsLeaf(Integer isLeaf) {
		this.isLeaf=isLeaf;
		return this;
	}
		
	/**
	 *@return the IsLeaf
	 */
	public Integer getIsLeaf() {
	    return this.isLeaf;
	}
/*---end-auto-generate-don't-update-this-area--*/	
}
